//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class task3
    {
        [Required]
        [StringLength(12)]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }

        public int id { get; set; }
        [Required]
        [StringLength(12)]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string E_mail { get; set; }
        [Required]
        [RegularExpression("((079)|(078)|(077)){1}[0-9]{7}", ErrorMessage = "Enter A Valid Jordanian Phone Number")]
        public string phone { get; set; }
        [Required]
        [Range(18, 50)]
        public int Age { get; set; }
         [Required]
        [StringLength(10)]
        [Display(Name = "Job Title")]
        public string jop_title { get; set; }
        [Required]
        public bool Gender { get; set; }
    }
}
