//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authentication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class task3
    {
        [Display(Name = "Name Product")]
        public string First_Name { get; set; }
        public int id { get; set; }
        [Display(Name = "price")]
        public string Last_Name { get; set; }
        [Display(Name = "category")]
        public string E_mail { get; set; }
        public string phone { get; set; }
        public Nullable<int> Age { get; set; }
        [Display(Name = "description")]
        public string jop_title { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string img { get; set; }
        public string filee { get; set; }
    }
}
